### ISSUE TITLE
Compilation Error under Xcode 6.2

### ISSUE THREAD

**Issue by Domsware** [FlexMonkey/SwiftCFD#2]
There are two compilation errors on the `FluidDynamicsRenderer.swift`:

- SwiftCFD/FluidDynamics/FluidDynamicsRenderer.swift:16:88: Method 'fromRaw' has been replaced with a property 'rawValue'
- SwiftCFD/FluidDynamics/FluidDynamicsRenderer.swift:28:12: Value of optional type 'UIImage?' not unwrapped; did you mean to use '!' or '?'?

**Comment by FlexMonkey** [comment]
Hi, that project is all updated now for Xcode 6.3 / Swift 1.2

Enjoy!

**Comment by FlexMonkey** [comment]
Now update for Xcode 7.2
